server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://wprsj.cn:3306/love?useSSL=false
    username: root
    password: wpr127912
    driver-class-name: com.mysql.cj.jdbc.Driver
  resources:
    static-locations: classpath:/static/
  redis:
    host: 127.0.0.1
    port: 6379
#    password: wpr127912
    lettuce:
      pool:
        max-active: 8
        max-idle: 8

oss:
  endpoint: oss-cn-chengdu.aliyuncs.com # OSS服务的Endpoint
  accessKeyId: LTAI5tD2dJvjSErbfq7NpFSQ        # AccessKeyId
  accessKeySecret: uyBtWvRlsDigVyVmxIuYNA6l98JOr4   # AccessKeySecret
  bucketName: ymcc-wpr # 存储空间名称
